# Generated by Django 3.2.6 on 2023-05-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'English'), (2, 'Spanish')], default=1, primary_key=True, serialize=False)),
                ('version', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
