# Generated by Django 3.2.6 on 2023-04-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weeks_days', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='program',
        ),
    ]
