# Generated by Django 3.2.6 on 2023-05-02 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        ('exercises_info', '0002_alter_exerciseinfo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)])),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])),
                ('index', models.PositiveSmallIntegerField()),
                ('rounds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('power', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rir', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rest', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('exercise_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises_info.exerciseinfo')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='programs.program')),
            ],
        ),
    ]
