# Generated by Django 3.2.6 on 2023-06-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='reps',
            new_name='unit_value',
        ),
    ]
