# Generated by Django 3.2.6 on 2023-04-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20230427_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='program',
        ),
        migrations.RemoveField(
            model_name='day',
            name='week',
        ),
        migrations.RemoveField(
            model_name='week',
            name='program',
        ),
    ]
