# Generated by Django 3.2.6 on 2023-04-27 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weeks_days', '0001_initial'),
        ('exercises', '0003_auto_20230427_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weeks_days.day'),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
