# Generated by Django 3.2.6 on 2023-06-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('version', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(choices=[(False, 'No released'), (True, 'Released')], default=False)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
