# Generated by Django 3.2.6 on 2023-04-26 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='training_id',
            new_name='training',
        ),
    ]
