# Generated by Django 3.2.6 on 2023-04-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_rename_training_id_program_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='must_know',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='requirements',
            field=models.TextField(null=True),
        ),
    ]
