# Generated by Django 3.2.6 on 2023-06-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises_info', '0001_initial'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseInfoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('version', models.PositiveSmallIntegerField()),
                ('exercise_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises_info.exerciseinfo')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
            ],
            options={
                'unique_together': {('exercise_info', 'language')},
            },
        ),
    ]
