# Generated by Django 3.2.6 on 2023-06-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseInfo',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('unique_id', models.CharField(max_length=32, unique=True)),
                ('version', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
