# Generated by Django 3.2.6 on 2023-05-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseInfo',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('version', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
