# Generated by Django 3.2.6 on 2023-06-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_info', '0003_alter_exerciseinfo_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseinfo',
            name='mode',
            field=models.BooleanField(choices=[(False, 'Reps'), (True, 'Time')], default=False),
        ),
    ]
