# Generated by Django 3.2.6 on 2023-06-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_info', '0005_rename_mode_exerciseinfo_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinfo',
            name='unit_type',
            field=models.SmallIntegerField(choices=[(0, 'Reps'), (1, 'Time')], default=False),
        ),
    ]
